version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./requirements.txt:/app/requirements.txt
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    command: uvicorn src.api.api:app --host 0.0.0.0 --port 8000 --reload
